### ISSUE TITLE
[Bug] ship monitors never re-enable upon returning to ship

### ISSUE THREAD

**Issue by JohnMetroid** [EugeneWWolf/VanillaMoonsLagFix#1]
hey there,

first off, I want to thank you for this mod.  You've absolutely nailed a bugfix for ship triggers causing extreme performance issues when coupled with certain mods.

However, it seems that returning to the ship doesn't occur correctly, and monitors/cams never re-enable.

Tested on march, with only the "mute button" mod installed (essentially vanilla + your mod).  The 2 vanilla monitors remain off, and internal cam/external cam/radar remain frozen upon return to ship

![image](https://github.com/user-attachments/assets/2cdbc6a1-54ab-4abd-9477-c2c15ce65582)

thanks :)

**Comment by EugeneWWolf** [comment]
Thank you for the bug report, I'm currently looking into it. I'll fix it in version 1.0.1.

**Comment by EugeneWWolf** [comment]
Hi, I fixed this bug in new version. I can't reproduce it anymore. If you'll find more issues, feel free to write an issue here.
Thank you!
@ajsglist
